Nanosecond timestamps primitive type, gated by Cargo feature.
This is a squashed commit of a lot of incremental work supporting
nanosecond timestamps

This includes adjusting the SchemaTransform for nanosecond timestamps

This drops support for encoding nanosecond timestamps into a null value
which was a failing test case. I believe this was previously done in
error sinec the other test cases for timestamps don't appear to support
nullable transforms

This change also fixes  and overflow in
estimated_owned_heap_size_on_table_with_many_log_files

When the nanosecond-timestamps feature is enabled, the generated columns
for this test exceed the size of an i64 causing:

     test snapshot::tests::estimated_owned_heap_size_on_table_with_many_log_files ... FAILED

     failures:

         snapshot::tests::estimated_owned_heap_size_on_table_with_many_log_files

     test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 2931 filtered out; finished in 0.40s
     thread '<unnamed>' (522675) panicked at test-utils/src/table_builder.rs:1407:26:
     attempt to multiply with overflow
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     thread 'snapshot::tests::estimated_owned_heap_size_on_table_with_many_log_files' (522674) panicked at test-utils/src/table_builder.rs:123:10:
     block_on_sync thread panicked: Any { .. }

Signed-off-by: R. Tyler Croy <rtyler@brokenco.de>